title: Buu Truong
logo: /assets/BT_02.jpeg
description: Hi, I am Buu Truong. I am a Medical Doctor from Vietnam with experience and passion in Statistical Genetics. I am currently a PhD student at Alkes Price lab at Harvard T.H. Chan School of Public Health and a computational biologist at Pradeep Natarajan lab at the Broad Institute of MIT and Harvard.
# show_downloads: true
theme: jekyll-theme-minimal
