theme: jekyll-theme-minimal
title: Welcome to Buu's website
description: Happy to connect with anyone interested in statistical genetics and computational biology
logo: https://media-exp1.licdn.com/dms/image/C5603AQG9OHfc7Nuc3Q/profile-displayphoto-shrink_200_200/0/1621998756163?e=1664409600&v=beta&t=uouW7hzJZemMlMUz45712tFCAMvAxz-gpWYdcckjARY
show_downloads: false