remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Welcome to Buu's website
description: Happy to connect with anyone interested in statistical genetics and computational biology